package com.aluralatam.ForoAlura.domain.usuario.model.utils;
public enum Countries {
    ARGENTINA,
    BOLIVIA,
    BRASIL,
    CHILE,
    COLOMBIA,
    COSTA_RICA,
    ECUADOR,
    EL_SALVADOR,
    GUATEMALA,
    HONDURAS,
    MEXICO,
    NICARAGUA,
    PANAMA,
    PARAGUAY,
    PERU,
    REPUBLICA_DOMINICANA,
    URUGUAY,
    VENEZUELA,
}